language: ruby
bundler_args: --without kitchen_vagrant --without development
rvm:
  - 1.9.3
cache:
  bundler: true
before_install:
  - sudo apt-get install -qq libgecode-dev
  - echo -n $DO_KEY_CHUNK_{0..30} >> ~/.ssh/id_do.base64
  - cat ~/.ssh/id_do.base64 | tr -d ' ' | base64 --decode > ~/.ssh/travis.pem
  - ls -la ~/.ssh
script:
  - bundle exec foodcritic -f any .
  - bundle exec rubocop
  - bundle exec rspec -fd
  - bundle exec kitchen test $KITCHEN_INSTANCE
after_script:
  - bundle exec kitchen destroy
branches:
  only:
  - master
env:
  global:
    - secure: T3iuLH3dNbZ3ydc/asltq1K4t6MaRx1vuxy7cSpHt7dXawjiwWav925Q1OehZ4PoyoLaQ1TGuubSDhX3m9NBCeJCQLU2hHl3E6+H13qcUxbivex8yvUTOVmxBRUvF6Yo0jT7DNNtsgl0uA2cUiZetkn5M9vGVoOwgZ5zoLWpgjE=
    - secure: q3ukTEfltSF1cFgnm6C3JUKuk8uaIqlZ/d2r+j1LeC8KD+Z8EboqzDViheXjp98Uk9T/2pMzoWxGC+aXZNgkzrP8TmOKaCusgn21ob+SoRt5TjHL+lgq0Yqmul6iv7a4Rspn3N69sBhFIhefI9qPGlfc/AChxwQU2+ziVNqJHZc=
    - secure: WbB+qsb9bPfsbRjq+/DqrCL6x8HzmCvO5bMMijCuige4zqwRr8Mc7PCeOA1ujMYQNIQiDAxJ7e3ikFH4eGIunuVZL9SkdD3NbkfAubrgBBq0UK+vkJ2OSIMCYFmDo6SCmpUPqOWTI4UA/uogkC9wOd7stuR1DNDwtGbDglF4oAY=
    - secure: Fn4C/iI6l2XiwWWwRE4jPgNu7DxGGGiL805jmlzwWycO9GLv/+4uHUrHZ+MnUIqfRh2i6LR+BM4HaWsXNsJ7pFepB/ul1y8CO7Z9bxarcW3FTeQrzMuphBkGF6Zs8Dws9jBFDlkE5Sb4hcjJmcXHnQXGaLc/PdCBSqOnY1ZhUUI=
    - secure: UiyP8lOKnF5z5SDG3Uc8VKxu2Q2jqFOq0OE8PuKKgusptVxd5EZxMSJE5Z6PKlHqMbsG9a2XyVBqzS4cPSGRbYOSacFfwWHsZanvyjsHAi2Op4Ar40qsXhVzUJrkFH8pWThfDMuGwL04ucq5LpE4NjdM9xv2SC9Tq+wRVZkOkpY=
    - secure: jYerWDGRAOtOntBodBe0LZXDTveBj4zlvq8GAiRM8s+QpjB3HSBmlicNCbhuQBkiaI8ZBHALElut7Fk64pzFIfNyiSmyePi3NMdGrD35B0t9D7rPrirRR7SqXi8joeISfDBV5AYoz8fuf7FT39amKF5CurP3YDdFMeyBZHtqI+o=
    - secure: msHOI6MslkTGAYow81bnHHtudpGiH6FgIkZSzJiYwoD/KUcn0K1qgGZ0XmTX5n4bNhQaMInQwQtVkPEnqmpOObqaI6871gORasWwd+4IuavVw1X0roaXJdXzU7J3r/4UwPK8CIDU5vDEOG8TbqhiRp7sBKHSTjipVqCC2jpBvgw=
    - secure: AYT7kOqTmJD6NvkcACxsvfYGz7RG5fdtx6kUi9An6pAPZjP3HmHM0wqIpg+2wqEFBpbU+SY3hWNZuyg44lPHNnxjcKj+2fR+OHfo9kHP8eVYjR0VSWCTuUQ4QMLgX4rbjOD8TjDvX5NurP6tGPG3SO3BPUyBwtveNYJm2QCwpc0=
    - secure: TYuHqXkb98FnbVwyHVDUfZxlTMoGqR5dciYn4VdVxmCMXJMllQFZHHiy0oXnc1X0U3RfZBl6V8+yg9LEBACmRm2GdWM6KKRUfN76MzW0zpFH5X16ccLumaXwnsxOyFCkuLFrLJPBbwIlB8NIfuGA58G8iz35sHPpk3k7o2LHY28=
    - secure: cxyARBuPvuEvQXPki7eoFLwqmN5uLPKiFO9dqJQwJ3O5+geyx6IjVe5cC8T0gZVSb2LZgeIClyUCpHnhp0RYmi9YZxvCdtPjPMBF4+tzm4T6gglKiwr2deea/OYoG2d2OcqD/JROlgI0BfcWP2H0nCjsjHGXELEHd+ENzdwMaUc=
    - secure: Mbluol1+Zd/nH/WvN2sjzvZRE8RxVi2oOQ+RZmX8PeLlZJQYh7+sT6Ckk1jA2AvzvpH3proj6L6hvAhhYOnYrqObTqemQ3Hd5V81H7eYHLF309Ea2wueRByq4XfoiQoJZNwl9dL7nDp4T6/P0F5UbQItlbPq2AcG+FRhBZ1fDdA=
    - secure: Bt4t53BgHq6SQlNYYnpYX+csFaxRoCCW1gMxCn6X7hC8l6crqaRtiMMwN9Nt0ujceJ9iwRRTTyOo9MEkArnwqVh9VpEM4YVzAC5ipD20GHJCrhmi2fVbSlg66ZfeSF41lCr3apYvs9g2T5rs+5B9Uz1xbgt8TLqboJvpdNdk3Sc=
    - secure: xElOtGUtvyIuwHJF7Bz5Oe/XZz1E86lVuaHhiewxt6LzKjC626mq39xS+TUgap7aqLTt+nn6WLEaxs3gqn8hDPCpBtY6NmNX+npWDjm50xxhLR+eawUSJE3gcM7bb/VpQ+nYlK6VA9W7HWP9AlXODgsKwPHYP4wb+AbZIoVjneY=
    - secure: OrF+GAzfRWzaPdeQ27VmL1oSrjBQ3u6PW3f0sPr3CiPvdmLFsIwJFNtRbsbZY0Kp13nVMUoe5LznQCDBwh6NAoXtNcA8AgYWXnYshQr48ko5ahN8PH0qdZ/4lmBpfH1Tu3h+WmcT+ZVRsrnFl1oAyqkA7pimilbblww1hnnndDE=
    - secure: lQVoe+YgVGvX4pGee9CmJuzuVkm4XPLOJuSyKst+yHXwNZASuRxCkiw7aogNw5lzEnoxt3RsWua36NCFodYDchQesL73Ss3l+bp91RedhWEIY4gAob4n20ghiPmTw4OcvXo540bXoZV9og8LxhZUrei83l5SQBpAmvBlUq0yOBI=
    - secure: Oh06jtNjrp8/sJuXX/so9lkBWeORYn1Cn9LGJ/lG1KDU3yt1mJKBCO0dsDC7O988SMmfBfuOwqkM8uYKLhVzSkOUNEXNPTidyIEi0PoCQ50jZzrGMjdSKDCOqU0ASt+U6WSM26pRf0EMG6oOmaRebWhXBL+yXI4bmSZFbRTLrcc=
    - secure: Db9NtBePxaBvBDozL9AI548ixJUOJGutmN01KBL6Zghu/jEzKhGVsBBRnWGkcERpuxPJMIb5OCdqxi7mjMjkcxRUODodBXfprEuctbY7w2rXnxqu4z3g3oH31s5880athIhxHqgK8uNNztsp7da2t4N7gcnuX66nI7PQAiG2S3g=
    - secure: whWqEXJWLRUAEh1EAXRb5G5dYziQeUzU2IggK9rAihMYLTVTHS+UMEbDr/L9lK7lnKJIpV2m5TLC4xZ91wIB1bl2+Oi4wQBqp2k1IVVvZtP/nFSpKX8rRIq0F5LQ+85yxDwultOfmdkJMiafzkJQLPfRnxXGjTQ4CM2cQzlqGo0=
    - secure: Xo1GtfSbKg80vxSB+SyorxSU1Mr5a86epna47e9KR9BuwSJ3Q4zf4K2hiPXplb9GbR1wRk9MRSYDtc61nreYkZnItwMDuZR1v8fX+ge6xzddfttDvpNDt2i5+NVLJw9cj8tbrB8+bhkh/U7bX0LWt60csWpe3NnhkwIkUT6EX7A=
    - secure: JqCXMR/rkiUMsVhLV/wGtecEBylUUW8rUVpP94YskLmMmgY35P3CRPDgD30u6XPD8d8CQPXRjLzkyulGZwwFItOKR7XjrA32hqt8R2LAy80W7eEeM8am4ybSL9VgEhndY6w4pId/tjuStcM5GJ6ufSYC71pYfcCUFpYsoe/AxxA=
    - secure: Gv0Pcx7nBjjo38uC1mQH732gFCMd1xCMQi5b8KYDXfP56qz5VF+WlmhMGzRPmGVZOtCGl7lmDZ5KuxKgkeGfzNn/olb+Ke8O4hoGlNPbe8F/rISxlxgZxkVmRZDv5zxkC2fik8EN9ZnwvrRY+pZUwrzwYzLROjFQ7G1Rz3dLAOs=
    - secure: iB+18NV6k2/tqTIhk8NIEhEVhpYishRIh66D7sUvMW5Sa/TIyWnqpX4pBQS+ZcxZntD86RDDU02TAeYgnMxFJxVtsHlS6JZ5j4X6UYPaDf8oZhjCewqMm6fZ1Ju0phscbAjZe+CLshRzGAGPIoc8NaxGH/YKfgHampj7TyddYLo=
    - secure: cCHXsjPUS0L8CDxUCQS8ClCr+n2cnkQrGNzMHWMLymrh3/OybVYmudyneISP089ftqjMHFZeHuFOJMi8oL3TgNEdd4o1+RXTVPgH7t5krjWmI1xEJxDTthRHfbsoQnxwsxgA1A6CJZH6QV2h+jxwe+mYC6hbOyBWBlhOmtFzHCk=
    - secure: EaZt2t6I/YsyPRw4EO1jxaTxfbb/kMPYExrd30jycmMG7mC9GkjHStrX3G3uCSWLDmK5o3jKTeJCYIZksBpjdIURb/7fbWbgeqY8bh0+E7C3TpUEBb5YF/thw2oWEv02aoBFbwFHAS68Xn4Gn13utTC5SEnYSLcvdOjtDv5/4Lc=
    - secure: p65XTl6uxJws5pjviw7PVBR0h9/v19gTnSyotAt7FLJIllciEgOGbUbTqViBwEkDJAhqpi+Kjr6GlWeuyNV+PfDuRJXEeR96WK5omzFhkjgx9FF/AA6+yZ6GWuxw7J1zrg/j6hluJmy2uM2DKACZiTvzvASFXjUa+xAuWskf80A=
    - secure: ObR4hbDses+0bxLrC+YQBi9y7eMzvQq3ld4YmMm/stJB6nCwDmzG94ouH1n+W1/Jt25RfKYeyScF+TNoXQgCtqD3NN2p7sLY71OPXqNJwatbl/7ymSD44NfhlfI8spFFW7e3k0eJaEKPwHoUvUbZ3er4y9K3rlcmsF5bVfmHToI=
    - secure: fI+ZC+TKOJztJ8A4Tu5Lr8P+zanguEeT7Zmns87iX1UN0umZL5imoxm5jatKbQL5t3rVr4hjwI4+XzZj8rJjSa5OeZwihaBY72555LCyJF0itA5kUUDQy7RPkJrZLfm9HIYTR5JPwLtt/Zc/nOOZIt0vARwhhYLDvR2fnBgnNr8=
    - secure: Jrh8HE+2dGuW+5OIaLlY8qFqinktr2lEB3pLO6ROJ5NMHeko/PsflqJkhlkpGaP0kQvXp1u52GXlpJVYgKWgikHrI0uidt+c9nMpEVqOAX/IL3Pn+djOdTMQpKI4AYm6UbepLpJCR2U5ugfPVY3aYTctho1E+LOjsN/smy+hQCg=
    - secure: oSomE5CtH6NPPyh3QQ1sK8wendgQ8XTTzMSxsdNgEDz1Vofm5DQVGY1j4JmaSc8BhrpZosnfglPj3imteVZb0fjoP8zGzsuy9mVZrMq/LifXsmkRFNiWCqA5C8NF+F38wzsIj8GMDsNOBekv/1ypnIRYHkzWWvwjjWg/xlxb8lw=
    - KITCHEN_INSTANCE='default-ubuntu-1204'
